[workers]
# Format: host:port:weight comma-separated
# For local testing:
nodes=localhost:8001:1,localhost:8002:1,localhost:8003:1
# For multi-machine:
# nodes=192.168.1.10:8001:2,192.168.1.11:8001:1

[tasks]
matrix_size=300
monte_carlo_samples=5000000
prime_count=200
prime_min=100000
prime_max=99999999
chunks_count=12
log_file_path=Dataset/accesslog.csv

[network]
connect_timeout_ms=10000
read_timeout_ms=120000
heartbeat_timeout_ms=5000
